/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorPicker: typeof import('./components/ColorPicker.vue')['default']
    CountdownCard: typeof import('./components/CountdownCard.vue')['default']
    DefaultHeader: typeof import('./components/layout/DefaultHeader.vue')['default']
    FloatDatePicker: typeof import('./components/ui/float-date-picker/FloatDatePicker.vue')['default']
    FloatInput: typeof import('./components/ui/float-input/FloatInput.vue')['default']
    FloatInputNumber: typeof import('./components/ui/float-input-number/FloatInputNumber.vue')['default']
    FloatSelect: typeof import('./components/ui/float-select/FloatSelect.vue')['default']
    FloatTimePicker: typeof import('./components/ui/float-time-picker/FloatTimePicker.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NH2: typeof import('naive-ui')['NH2']
    NH3: typeof import('naive-ui')['NH3']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NModal: typeof import('naive-ui')['NModal']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTimePicker: typeof import('naive-ui')['NTimePicker']
    OffTimeSetting: typeof import('./components/OffTimeSetting.vue')['default']
    RemindList: typeof import('./components/RemindList.vue')['default']
    RemindStyleSelect: typeof import('./components/RemindStyleSelect.vue')['default']
    RepeatSetting: typeof import('./components/RepeatSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SquidwardRemind: typeof import('./components/reminds/SquidwardRemind.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
  }
}

// For TSX support
declare global {
  const ColorPicker: typeof import('./components/ColorPicker.vue')['default']
  const CountdownCard: typeof import('./components/CountdownCard.vue')['default']
  const DefaultHeader: typeof import('./components/layout/DefaultHeader.vue')['default']
  const FloatDatePicker: typeof import('./components/ui/float-date-picker/FloatDatePicker.vue')['default']
  const FloatInput: typeof import('./components/ui/float-input/FloatInput.vue')['default']
  const FloatInputNumber: typeof import('./components/ui/float-input-number/FloatInputNumber.vue')['default']
  const FloatSelect: typeof import('./components/ui/float-select/FloatSelect.vue')['default']
  const FloatTimePicker: typeof import('./components/ui/float-time-picker/FloatTimePicker.vue')['default']
  const NAvatar: typeof import('naive-ui')['NAvatar']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NColorPicker: typeof import('naive-ui')['NColorPicker']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDatePicker: typeof import('naive-ui')['NDatePicker']
  const NDivider: typeof import('naive-ui')['NDivider']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NEllipsis: typeof import('naive-ui')['NEllipsis']
  const NEmpty: typeof import('naive-ui')['NEmpty']
  const NGi: typeof import('naive-ui')['NGi']
  const NGrid: typeof import('naive-ui')['NGrid']
  const NH2: typeof import('naive-ui')['NH2']
  const NH3: typeof import('naive-ui')['NH3']
  const NInput: typeof import('naive-ui')['NInput']
  const NInputNumber: typeof import('naive-ui')['NInputNumber']
  const NList: typeof import('naive-ui')['NList']
  const NListItem: typeof import('naive-ui')['NListItem']
  const NModal: typeof import('naive-ui')['NModal']
  const NPopconfirm: typeof import('naive-ui')['NPopconfirm']
  const NScrollbar: typeof import('naive-ui')['NScrollbar']
  const NSelect: typeof import('naive-ui')['NSelect']
  const NTag: typeof import('naive-ui')['NTag']
  const NText: typeof import('naive-ui')['NText']
  const NTimePicker: typeof import('naive-ui')['NTimePicker']
  const OffTimeSetting: typeof import('./components/OffTimeSetting.vue')['default']
  const RemindList: typeof import('./components/RemindList.vue')['default']
  const RemindStyleSelect: typeof import('./components/RemindStyleSelect.vue')['default']
  const RepeatSetting: typeof import('./components/RepeatSetting.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SquidwardRemind: typeof import('./components/reminds/SquidwardRemind.vue')['default']
  const ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
}