// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CheckForUpdate():Promise<services.UpdateResult>;

export function CloseRemind():Promise<void>;

export function DisableAutoStart():Promise<void>;

export function DownloadAndInstall(arg1:string):Promise<void>;

export function EnableAutoStart():Promise<void>;

export function GetRemindAdvanceMinutes():Promise<number>;

export function GetRemindMode():Promise<string>;

export function GetRemindOffTime():Promise<string>;

export function GetRemindStyle():Promise<string>;

export function GetTodoTitle():Promise<string>;

export function GetVersion():Promise<string>;

export function IsAutoStartEnabled():Promise<boolean>;

export function IsRemindWindow():Promise<boolean>;

export function ShowRemind(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SyncRemindConfig(arg1:string,arg2:number,arg3:Array<number>,arg4:string):Promise<void>;
