// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseRemind():Promise<void>;

export function GetRemindMode():Promise<string>;

export function GetRemindStyle():Promise<string>;

export function IsRemindWindow():Promise<boolean>;

export function ShowRemind(arg1:string,arg2:string):Promise<void>;

export function SyncRemindConfig(arg1:string,arg2:number,arg3:Array<number>,arg4:string):Promise<void>;
