// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseRemind() {
  return window['go']['main']['App']['CloseRemind']();
}

export function GetRemindMode() {
  return window['go']['main']['App']['GetRemindMode']();
}

export function GetRemindStyle() {
  return window['go']['main']['App']['GetRemindStyle']();
}

export function IsRemindWindow() {
  return window['go']['main']['App']['IsRemindWindow']();
}

export function ShowRemind(arg1, arg2) {
  return window['go']['main']['App']['ShowRemind'](arg1, arg2);
}

export function SyncRemindConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SyncRemindConfig'](arg1, arg2, arg3, arg4);
}
