// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CloseRemind() {
  return window['go']['main']['App']['CloseRemind']();
}

export function DisableAutoStart() {
  return window['go']['main']['App']['DisableAutoStart']();
}

export function DownloadAndInstall(arg1) {
  return window['go']['main']['App']['DownloadAndInstall'](arg1);
}

export function EnableAutoStart() {
  return window['go']['main']['App']['EnableAutoStart']();
}

export function ExitApp() {
  return window['go']['main']['App']['ExitApp']();
}

export function GetRemindAdvanceMinutes() {
  return window['go']['main']['App']['GetRemindAdvanceMinutes']();
}

export function GetRemindMode() {
  return window['go']['main']['App']['GetRemindMode']();
}

export function GetRemindOffTime() {
  return window['go']['main']['App']['GetRemindOffTime']();
}

export function GetRemindStyle() {
  return window['go']['main']['App']['GetRemindStyle']();
}

export function GetTodoTitle() {
  return window['go']['main']['App']['GetTodoTitle']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsAutoStartEnabled() {
  return window['go']['main']['App']['IsAutoStartEnabled']();
}

export function IsRemindWindow() {
  return window['go']['main']['App']['IsRemindWindow']();
}

export function ShowRemind(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowRemind'](arg1, arg2, arg3);
}

export function SyncRemindConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SyncRemindConfig'](arg1, arg2, arg3, arg4);
}
